### ISSUE TITLE
C-Sharp SDK - Start working on Data Entities module

### ISSUE THREAD

**Issue by pavanrawoor** [Build-Squad/arbitrum-csharp-sdk#1]
- Start working with the Data Entities module
- Create new classes and add unit test cases for all the clases.  
- Use phython or TypeScript SDK as reference

**Comment by ranaabhishek172** [comment]
1. Did Initial Commit and Added Readme file.
2. Added DataEntities classes and test cases.
3. Added ABI files.
4. Added few Utils classes.

**Comment by ranaabhishek172** [comment]
1. Added positive and negative unit test cases for network class:

![image](https://github.com/Build-Squad/arbitrum-csharp-sdk/assets/151494725/66eadf56-693b-4ba3-9b1d-5403406fb309)

2. Fixed some minor issues.

**Comment by ranaabhishek172** [comment]
Module completed.
