### ISSUE TITLE
C-Sharp SDK - Start working on Message module

### ISSUE THREAD

**Issue by pavanrawoor** [Build-Squad/arbitrum-csharp-sdk#2]
- Start working with the Message module
- Create new classes and add unit test cases for all the classes.
- Use python or TypeScript SDK as reference

**Comment by ranaabhishek172** [comment]
Created https://github.com/Build-Squad/arbitrum-csharp-sdk/pull/4

**Comment by ranaabhishek172** [comment]
Module completed.
