### ISSUE TITLE
C-Sharp SDK - Scripts for Test Set-up

### ISSUE THREAD

**Issue by pavanrawoor** [Build-Squad/arbitrum-csharp-sdk#5]
- Write a C# scripts for creating a test set-up and deploying abi contracts. 
1. Configuring and initializing a web3 provider for Ethereum and Arbitrum networks. 
2. Setting up deployers, signing transactions.

**Comment by ranaabhishek172** [comment]
Created https://github.com/Build-Squad/arbitrum-csharp-sdk/pull/7

**Comment by ranaabhishek172** [comment]
Pull request merged
