### ISSUE TITLE
C-Sharp SDK - Resolve errors and exceptions

### ISSUE THREAD

**Issue by pavanrawoor** [Build-Squad/arbitrum-csharp-sdk#6]
-  Resolve errors and exceptions

**Comment by ranaabhishek172** [comment]
Currently getting while depositing Eth

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  HResult=0x80131500
  Message=Cannot convert type 'Arbitrum.DataEntities.SignerOrProvider' to 'string'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Arbitrum.DataEntities.SignerProviderUtils.<CheckNetworkMatches>d__5.MoveNext() in C:\arbitrum-dev\src\lib\DataEntities\SignerOrProvider.cs:line 133
   at Arbitrum.AssetBridgerModule.AssetBridger`3.<CheckL1Network>d__5.MoveNext() in C:\arbitrum-dev\src\lib\AssetBridger\AssetBridger.cs:line 40
   at Arbitrum.AssetBridgerModule.EthBridger.<Deposit>d__6.MoveNext() in C:\arbitrum-dev\src\lib\AssetBridger\EthBridger.cs:line 159
   at Program.<Main>d__0.MoveNext() in C:\Users\Admin\Downloads\ArbitrumTutorials\EthDeposit\Program.cs:line 52
   
   
   
   Working on the fix.

**Comment by ranaabhishek172** [comment]
System.Exception : Invalid account used signing

  Stack Trace: 
AccountSignerTransactionManager.SignAndSendTransactionAsync(TransactionInput transaction)
AccountSignerTransactionManager.SendTransactionAsync(TransactionInput transactionInput)
TransactionReceiptPollingService.SendRequestAndWaitForReceiptAsync(Func`1 transactionFunction, CancellationToken cancellationToken)
CallSite.Target(Closure, CallSite, Object)
UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
EthBridger.Deposit(Object parameters) line 213
EthDepositTesting.EthDepositTest() line 57
GenericAdapter`1.BlockUntilCompleted()
NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass3_0.<PerformWork>b__0()
<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ContextUtils.DoIsolated(ContextCallback callback, Object state)
ContextUtils.DoIsolated[T](Func`1 func)
SimpleWorkItem.PerformWork()

**Comment by ranaabhishek172** [comment]
Nethereum.JsonRpc.Client.RpcResponseException : invalid remainder: eth_sendRawTransaction

found a workaround for this issue here
https://github.com/trufflesuite/ganache/issues/1114

**Comment by ranaabhishek172** [comment]
Nethereum.JsonRpc.Client.RpcResponseException : intrinsic gas too low: eth_sendRawTransaction

**Comment by ranaabhishek172** [comment]
Nethereum.JsonRpc.Client.RpcResponseException : insufficient funds for gas * price + value: eth_sendRawTransaction

workaround for this issue:
https://github.com/Nethereum/Nethereum/issues/384

**Comment by ranaabhishek172** [comment]
> ```
> Nethereum.JsonRpc.Client.RpcResponseException : intrinsic gas too low: eth_sendRawTransaction
> ```

Description of this issue :
https://ethereum.stackexchange.com/questions/1570/what-does-intrinsic-gas-too-low-mean

**Comment by ranaabhishek172** [comment]
> Nethereum.JsonRpc.Client.RpcResponseException : The field to must have byte length of 20: eth_estimateGas

opened a new issue to Nethereum for resolution:
https://github.com/Nethereum/Nethereum/issues/1029

**Comment by AmarildoGrembi** [comment]
If I am not mistaken, have we found a workaround for this already?

**Comment by ranaabhishek172** [comment]
> If I am not mistaken, have we found a workaround for this already?

Yes @AmarildoGrembi , closing the issue
